### ISSUE TITLE
Multilib Required on Linux

### ISSUE THREAD

**Issue by oldtopman** [d0k3/Universal-Inject-Generator#12]
There are three binaries included with this program: 3dstool, ctrtool, and MergeExHeader. 3dstool and MergeExHeader are 32 bit applications, and ctrtool is a 64 bit application. This means that regardless of which architecture the script is run on, a multilib installation is required.

I think that if possible, the architectures should match on the bundled application. It would be really nice if both 32 and 64 bit versions could be distributed as well. At the very least, it should be mentioned as a requirement for linux users on the readme.

**Comment by d0k3** [comment]
I assigned @dark-samus :P. Can you look into this? I am not a Linux user personally.

**Comment by pixel-stuck** [comment]
@oldtopman I have a 64bit system and have developed this and run it on my own system multiple times, nothing else required, though I do use Ubuntu, since I'm lazy with my OS installs, so that may be why... These binaries are downloaded directly from the tool distributors release page, except mergeexheader, of which the source is included, if you'd like to provide an easy, clean method of detecting 64 bit linux and opening the correct binary (see process.sh) then I'd be happy to do this for you, I really like the current solution for detecting the OS, keeps it light and portable...

**Comment by oldtopman** [comment]
If it's alright with the two of you, I would like to provide both 32 and 64 bit versions of the binaries, then select whichever is appropriate for the current linux platform. This does mean that the 64 bit MEH and 3dstool utilities, as well as the 32 bit ctrtool wouldn't be from their release pages though.

For detecting architecture, I would use uname -m, but only on linux. I can write up what I'm talking about if it's something you would be interested in moving forwards with.

**Comment by pixel-stuck** [comment]
I can easily provide the binaries, I don't mind building them, but I don't want some super specific thing just for linux, I'd like to keep it as portable as possible to all unix-likes, if you can swing that then I'm all ears :)

**Comment by d0k3** [comment]
Yup, seconding that. We don't want to break OS X support
