### ISSUE TITLE
Do this on the 3DS itself?

### ISSUE THREAD

**Issue by JohnVeness** [d0k3/Universal-Inject-Generator#20]
As the Plailect guide says at https://github.com/Plailect/Guide/wiki/FAQ:

> Q: Can I do this without a computer (e.g. an Android phone)?
> A: This guide, as of now, requires a computer to inject FBI into Health & Safety.

It would be great if it was possible to inject FBI into H&S using software on the 3DS itself, e.g. in H9 or D9. Is this possible? If it was, everything else in the Plailect guide could be done just by copying and renaming files, so could be done, with some effort, on an Android phone or tablet.

**Comment by d0k3** [comment]
You're not the first one to suggest this. Creating the injectable is not done on console because it is quite a complicated process and involves multiple advanced tools (just take a look at the /tools subfolder). I am not adverse to someone else putting the work in to make this work (it is not impossible, just requries a ton of work), but I won't do it.
